### ISSUE TITLE
ED25519 or rsa-sha2-256 support

### ISSUE THREAD

**Issue by TheBFT** [vancluever/ssh_keygen#4]
Since RHEL 9 and other distributions based off this version (OL9 for instance) will no longer support standard RSA keys (see depreciation of SHA1 and related posts below), there's a growing need for ED25519 support or the ability to choose rsa-sha2-256 as the key type

https://docs.oracle.com/en/operating-systems/oracle-linux/9/relnotes9.2/ol9-DeprecatedFeatures.html#topic_ut5_3rn_1vb
https://access.redhat.com/solutions/6966079

**Comment by vancluever** [comment]
Hey @TheBFT, I haven't worked on this repository in a *very* long time, and I don't plan on making any more changes. Sorry!

If you found it useful so far, that's awesome! If you want to build on it, feel free to fork it and put a new version up on Supermarket.

Cheers!
